services:
  - type: static
    name: building-react-app
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: CI
        value: false